### A simple HelloWorld for TensorFlow

#### 1. Set up TensorFlow

In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.3.0


#### 2. Load a dataset
https://www.tensorflow.org/tutorials/quickstart/beginner
Load and prepare the MNIST dataset. Convert the sample data from integers to floating-point numbers:

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11493376/11490434 [==============================] - 2s 0us/step


#### 3. Build a machine learning model
Build a tf.keras.Sequential model by stacking layers

In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.28560755,  0.3211351 ,  0.15893784, -0.28677383, -0.06086966,
        -0.74478686, -0.44838756,  0.2242642 ,  0.02758363, -0.158223  ]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.13550042, 0.14040096, 0.11937921, 0.07644667, 0.0958225 ,
        0.04835552, 0.06503852, 0.12743819, 0.10468448, 0.08693357]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

3.0291748

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2922 - accuracy: 0.9148
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1416 - accuracy: 0.9576
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1035 - accuracy: 0.9677
Epoch 4/5
1875/1875 [==============================] - 2s 977us/step - loss: 0.0852 - accuracy: 0.9738
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0730 - accuracy: 0.9768


In [10]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0706 - accuracy: 0.9781


[0.07061591744422913, 0.9781000018119812]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[7.9525415e-07, 1.8844995e-08, 2.7076961e-05, 1.9040061e-04,
        2.2201885e-10, 4.7863598e-08, 1.2438360e-11, 9.9974948e-01,
        3.4987065e-07, 3.1772892e-05],
       [1.6627688e-06, 7.7732140e-05, 9.9966288e-01, 2.2096573e-04,
        1.2048592e-13, 4.4850767e-06, 2.5703509e-06, 5.0181933e-15,
        2.9620312e-05, 2.8779312e-12],
       [1.1202766e-07, 9.9850416e-01, 2.7435697e-05, 3.1331547e-06,
        6.4731823e-05, 3.6329775e-06, 4.5964530e-06, 1.3058193e-03,
        8.3503670e-05, 2.8883635e-06],
       [9.9992383e-01, 1.3882503e-09, 2.4758333e-06, 5.3284776e-07,
        1.0845299e-07, 1.6219648e-05, 1.9880479e-05, 9.5084242e-06,
        6.5634649e-09, 2.7467631e-05],
       [7.3272361e-07, 4.3067695e-07, 2.4324758e-05, 1.3170867e-07,
        9.9775463e-01, 3.0629888e-06, 6.5563231e-06, 2.7601796e-04,
        1.8195160e-06, 1.9323042e-03]], dtype=float32)>